### ISSUE TITLE
Wrong start date

### ISSUE THREAD

**Issue by Baltivisconti12** [fivemland/fl_punishment#1]
Hello, the start date of the sanction is wrong for me (If I place it at 9:00 p.m., on the poster it says 11:00 p.m.). I would also like to translate; "task left", ""reason" and "start date". I can't find the file where I can translate those words, could you tell me? Thanks
![image](https://user-images.githubusercontent.com/79205193/200703280-09cfb6ec-bc70-4a64-a87e-26215b0450b4.png)

**Comment by CsokiHUN** [comment]
I added the language files, you can easily translate everything.
I will check the dates.
