### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by kikotolo** [fivemland/fl_punishment#4]
sorry i have un problem a put everything in the file esx but when i make  the command "/comserv or adminjail" nothing happen.
can any one help me please?

**Comment by kikotolo** [comment]
yes i can this afternoon ghen i come back from work.
i have another issue when i started the scrip the commands dont work and all playera are teleported to the coords off admin jail and cant live. the only command working is /punishements and the nobody is in admin jail our comserv but we are stuck in de adminjail coords

**Comment by kikotolo** [comment]
I sorry the video is here https://youtu.be/FzFVFywot08

**Comment by kikotolo** [comment]
![Capture d'écran_20230126_142928](https://user-images.githubusercontent.com/31274920/214850665-2a22f8ab-2d26-49ab-acc7-9e0be265fa74.png)
and when a make the video i see in the console this error 
@sadam376

**Comment by CsokiHUN** [comment]
Try it now, I should have fixed the problem @kikotolo 
Use the latest version of the main branch.
