### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by cjosephdc** [fivemland/fl_punishment#6]
![image](https://user-images.githubusercontent.com/87730839/216397056-226428ef-853e-4c86-b096-319f4fbe1450.png)

**Comment by CsokiHUN** [comment]
I think it's fixed, try the latest version

**Comment by cjosephdc** [comment]
Im using the latest. Re-downloaded just now.

**Comment by cjosephdc** [comment]
Ow. you made new changes. Ill try again

**Comment by cjosephdc** [comment]
![image](https://user-images.githubusercontent.com/87730839/216400175-c1bb58ec-fd56-49bd-ae9d-359a548de566.png)
New error after sending player to comserv.

**Comment by cjosephdc** [comment]
![image](https://user-images.githubusercontent.com/87730839/216401288-5202dbea-1149-4a2e-85e4-ff04a1b3d26a.png)
NVM. I just changed the database to VarChar instead of text
